"""added youtuber for post to distinguish between articles and videos

Revision ID: 5d0bf5407b8d
Revises: f7ebbe24f2e0
Create Date: 2023-08-07 17:08:51.542457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0bf5407b8d'
down_revision = 'f7ebbe24f2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('youtuber', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('youtuber')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
