"""added name to api db

Revision ID: b1f09dc09e4a
Revises: 5d0bf5407b8d
Create Date: 2023-08-20 18:45:12.367103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f09dc09e4a'
down_revision = '5d0bf5407b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
